package main.common.model;

import java.net.URI;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlTransient;

import org.glassfish.jersey.linking.InjectLink;
import org.glassfish.jersey.linking.InjectLink.Style;

/**
 * Generic Entity for providing meta-data.
 * 
 */
@SuppressWarnings("serial")
@MappedSuperclass
public abstract class GenericEntityWithMeta extends GenericEntityWithUuid {

    /**
     * Generated id. Is always generated by JPA. Should not be provided by business logic.
     */
    @XmlTransient
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    /**
     * Generated UUID. Is generated before persisting (PrePersist)
     */
    @Column(length = 36)
    protected String uuid;

    /**
     * Date of creation. Is set before persisting (PrePersist)
     */
    protected Date createDate;

    /**
     * Created by principal. Is set by using ManagedCrudBean for persist/update
     */
    protected String createPrincipal;

    /**
     * Date of update. Is set before persisting (PrePersist) and updating (PreUpdate).
     */
    protected Date updateDate;

    /**
     * Updated by principal. Is set by using ManagedCrudBean for persist/update.
     */
    protected String updatePrincipal;

    /**
     * Self
     */
    @Transient
    @InjectLink(value = "/${resource.uriInfo.path}", style = Style.ABSOLUTE)
    protected URI self;

    public GenericEntityWithMeta() {
    }

    @Override
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCreatePrincipal() {
        return createPrincipal;
    }

    public void setCreatePrincipal(String createPrincipal) {
        this.createPrincipal = createPrincipal;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getUpdatePrincipal() {
        return updatePrincipal;
    }

    public void setUpdatePrincipal(String updatePrincipal) {
        this.updatePrincipal = updatePrincipal;
    }

    public boolean hasChanged() {
        return updateDate.compareTo(createDate) > 0;
    }

    public URI getSelf() {
        return self;
    }

    /*
     * Various
     */

    @PrePersist
    void createdAt() {
        this.uuid = UUID.randomUUID().toString();
        this.createDate = this.updateDate = new Date();
    }

    @PreUpdate
    void updatedAt() {
        this.updateDate = new Date();
    }

    @Override
    public String toString() {
        return "GenericEntityWithMeta [id=" + id + ", uuid=" + uuid + ", createDate=" + createDate + ", createPrincipal="
                + createPrincipal + ", updateDate=" + updateDate + ", updatePrincipal=" + updatePrincipal + ", self=" + self
                + "]";
    }

}
